version: '3'

services:
  mysql:
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: 'eRPbnQTFneKc'
      MYSQL_DATABASE: circle_core
      MYSQL_USER: circle_core
      MYSQL_PASSWORD: YQ75GU76Cp7R

    # ports:
    #   - 3306:3306

    volumes:
      - ./tmp/docker-compose/mysql:/var/lib/mysql

  circle_core:
    image: circle-core:latest

    command: ["--debug", "run"]

    depends_on:
      - mysql

    environment:
      DB_URL: 'mysql+pymysql://circle_core:YQ75GU76Cp7R@mysql/circle_core'

    ports:
      - 8080:8080
    
    volumes:
      - ./tmp/docker-compose/circle_core:/app/data
