"""add `cc_uuid` to schemas, modules

Revision ID: 0b8528a90b40
Revises: 017a329f79bf
Create Date: 2017-02-13 22:06:15.685142

"""
from alembic import op

import sqlalchemy as sa
from sqlalchemy.types import CHAR

# revision identifiers, used by Alembic.
revision = '0b8528a90b40'
down_revision = '017a329f79bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cc_uuid', CHAR(32), nullable=False))
        batch_op.create_foreign_key('fk_modules_cc_uuid', 'cc_informations', ['cc_uuid'], ['uuid'])

    with op.batch_alter_table('schemas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cc_uuid', CHAR(32), nullable=False))
        batch_op.create_foreign_key('fk_schemas_cc_uuid', 'cc_informations', ['cc_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schemas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_schemas_cc_uuid', type_='foreignkey')
        batch_op.drop_column('cc_uuid')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_modules_cc_uuid', type_='foreignkey')
        batch_op.drop_column('cc_uuid')

    # ### end Alembic commands ###
