"""modules rename column name from properties to attributes

Revision ID: 62c34208d16c
Revises: e3eb73695193
Create Date: 2017-02-28 13:40:14.934773

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '62c34208d16c'
down_revision = 'e3eb73695193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('properties', new_column_name='attributes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('attributes', new_column_name='properties')

    # ### end Alembic commands ###
