"""add `token` to users

Revision ID: 660e5c6052d1
Revises: 62c34208d16c
Create Date: 2019-01-10 16:27:24.295083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660e5c6052d1'
down_revision = '62c34208d16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.CHAR(length=128)))
        batch_op.create_unique_constraint('unique_constraint_token', ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_constraint_token', type_='unique')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
