"""add_relationship_between_replication_master_and_modules

Revision ID: e3eb73695193
Revises: d32fc4bb4af0
Create Date: 2017-02-24 17:20:34.164601

"""
from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e3eb73695193'
down_revision = 'd32fc4bb4af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replication_master_id', sa.Integer))
        batch_op.create_foreign_key(
            'fk_replication_master_id', 'replication_masters', ['replication_master_id'], ['replication_master_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_replication_master_id', type_='foreignkey')
        batch_op.drop_column('replication_master_id')

    # ### end Alembic commands ###
