# -*- coding: utf-8 -*-

from typing import Any, List, Tuple
from ..models import Device

def cli_device(ctx: Any) -> None: ...
def device_list(ctx: Any) -> None: ...
def _format_for_columns(devices: List[Device]) -> Tuple[List[List[str]], List[str]]: ...
