from typing import Any, List, Tuple
from ..models import Device

def cli_device(ctx: Any): ...
def device_list(ctx: Any): ...
def format_for_columns(devices: List[Device]) -> Tuple[List[List[str]], List[str]]: ...
def output_listing_columns(data: List[List[str]], header: List[str]) -> None: ...
def create_row_strings(rows: List[List[str]]) -> Tuple[List[str], int]: ...
