# -*- coding: utf-8 -*-

from typing import Any, List, Tuple
from ..models import Schema

def cli_schema(ctx: Any) -> None: ...
def schema_list(ctx: Any) -> None: ...
def _format_for_columns(schemas: List[Schema]) -> Tuple[List[List[str]], List[str]]: ...
