# -*- coding: utf-8 -*-

from typing import Any, Dict, List, Tuple

def output_listing_columns(data: List[List[str]], header: List[str]) -> None: ...
def create_row_strings(rows: List[List[str]]) -> Tuple[List[str], int]: ...
def stringify_dict(dic: Dict[str, Any]) -> str: ...
